version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - mvn install -DskipTests

  build:
    commands:
      - echo "Building the JAR file..."
      - mvn clean package -DskipTests

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  base-directory: target
